language: cpp
os:
    - linux-ppc64le
    - linux
dist: xenial
compiler:
  - gcc
  - clang
sudo: required

addons:
    apt:
        update: true
        packages:
            - texlive
            - texlive-generic-recommended
            - texlive-extra-utils
            - texlive-latex-extra
            - texlive-font-utils
            - ghostscript
            - libxml2-utils
            - cmake
            - cmake-data

jobs:
    include:
        - os: osx
          compiler: clang

before_script:
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
        sudo mkdir -p /usr/local/man;
        sudo chown -R "${USER}:admin" /usr/local/man;
        pip install --quiet conan;
        export HOMEBREW_NO_AUTO_UPDATE=1;
        brew install ghostscript;

        travis_wait brew cask install mactex-no-gui;
        curl -O -L http://mirrors.ctan.org/support/epstopdf.zip;
        unzip epstopdf.zip;
        mkdir -p /Users/travis/Library/TeX/texbin/;
        mv epstopdf/epstopdf.pl /Users/travis/Library/TeX/texbin/epstopdf;
        chmod a+x /Users/travis/Library/TeX/texbin/epstopdf;
        rm -rf epstopdf*;
        export PATH=/Users/travis/Library/TeX/texbin:/Library/TeX/texbin:$PATH;

        conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan;
        printf "[requires]\n
        libxml2/2.9.8@bincrafters/stable\n
        qt/5.11.3@bincrafters/stable" >> conanfile.txt;
        conan install . -g virtualrunenv;
        source activate_run.sh;
      fi;

script:
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles" -Dbuild_doc=ON -Dbuild_wizard=ON ..
    - make
    - make tests
    - make docs
