language: cpp
os: linux
dist: xenial
compiler:
  - gcc
  - clang

addons:
    apt:
        update: true
        packages:
            - texlive
            - texlive-generic-recommended
            - texlive-extra-utils
            - texlive-latex-extra
            - texlive-font-utils
            - ghostscript

linux-ppc64le: &linux-ppc64le
  os: linux-ppc64le
  env:
      - OS_NAME="linux-ppc64le"
  addons:
      apt:
          update: true
          packages:
              - texlive
              - texlive-generic-recommended
              - texlive-extra-utils
              - texlive-latex-extra
              - texlive-font-utils
              - ghostscript
              - libxml2-utils
              - cmake
              - cmake-data

linux-s390x: &linux-s390x
  os: linux
  arch: s390x
  dist: bionic
  env:
      - OS_NAME="linux-s390x"
  addons:
      apt:
          update: true
          packages:
              - texlive
              - texlive-generic-recommended
              - texlive-extra-utils
              - texlive-latex-extra
              - texlive-font-utils
              - ghostscript
              - libxml2-utils
              - cmake
              - cmake-data
              - qt5-default

jobs:
    include:
#        - <<: *linux-ppc64le
#          compiler: gcc
#        - <<: *linux-ppc64le
#          compiler: clang
#        - <<: *linux-s390x
#          compiler: gcc
#        - <<: *linux-s390x
#          compiler: clang
#        - os: osx
#          compiler: clang
#          addons:
#              homebrew:
#                  packages:
#                      - ghostscript
#                      - bison
#                      - flex
#                  casks:
#                      - mactex-no-gui

before_script:
    - |
      if [ "${TRAVIS_OS_NAME}" == "linux" ] && [ ! "${OS_NAME}" == "linux-ppc64le" ] && [ ! "${OS_NAME}" == "linux-s390x" ]; then
        printf "[requires]
        libxml2/2.9.9@bincrafters/stable
        libiconv/1.15@bincrafters/stable" >> conanfile.txt;
      fi;
      if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
        printf "[requires]
        bzip2/1.0.8@bincrafters/stable
        libxml2/2.9.9@bincrafters/stable
        libiconv/1.15@bincrafters/stable
        qt/5.12.0@bincrafters/stable
        bison/3.3.2@bincrafters/stable 
        [options]
        qt:shared=True" >> conanfile.txt;
      fi;
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
        pip install --quiet --user conan;
      fi;
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
        pip install --upgrade pip;
        pip install --quiet conan;

        curl -O -L http://mirrors.ctan.org/support/epstopdf.zip;
        unzip epstopdf.zip;
        mkdir -p /Users/travis/Library/TeX/texbin/;
        mv epstopdf/epstopdf.pl /Users/travis/Library/TeX/texbin/epstopdf;
        chmod a+x /Users/travis/Library/TeX/texbin/epstopdf;
        rm -rf epstopdf*;
        export CMAKE_INCLUDE_PATH="/usr/local/opt/flex/include;$CMAKE_INCLUDE_PATH";
        export CMAKE_LIBRARY_PATH="/usr/local/opt/flex/lib;/usr/local/opt/bison/lib;$CMAKE_LIBRARY_PATH";
        export PATH="/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:/Users/travis/Library/TeX/texbin:/Library/TeX/texbin:$PATH";
      fi;
    - if [ ! "${OS_NAME}" == "linux-ppc64le" ] && [ ! "${OS_NAME}" == "linux-s390x" ]; then
        conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan;
        conan install . -g virtualrunenv --build missing --update;
        source activate_run.sh;
      fi;

script:
    - mkdir build
    - cd build
    - cmake --version;
    - cmake -G "Unix Makefiles" -Dbuild_doc=ON -Dbuild_wizard=ON ..
    - make
    - if [ ! "${TRAVIS_OS_NAME}" == "osx" ]; then
        make tests;
        make docs;
        make tests && make docs;
      fi;
