language: cpp
compiler:
  - gcc
before_install:
    - sudo add-apt-repository ppa:texlive-backports/ppa -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq  texlive texlive-extra-utils texlive-latex-extra libxml2-utils

script:
    - mkdir build
    - cd build
    - ../cmake-3.1.0-Linux-x86_64/bin/cmake -G "Unix Makefiles" -Dbuild_doc=ON -Dbuild_wizard=ON ..
    - make
    - make tests
    - make docs
