language: cpp
compiler:
  - gcc
  - clang

before_install:
    - sudo apt-add-repository ppa:smspillaz/cmake-2.8.12 -y
    - sudo add-apt-repository ppa:texlive-backports/ppa -y
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq texlive
    - sudo apt-get install -qq texlive-extra-utils
    - sudo apt-get install -q -y texlive-latex-extra
    - sudo apt-get install -qq libxml2-utils
    - sudo apt-get install -qq cmake cmake-data

script:
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles" -Dbuild_doc=ON -Dbuild_wizard=ON ..
    - make
    - make tests
    - make docs
